"use client";
import {useState} from "react";
const questions=[
{tag:"FIRST IMPRESSION",q:"Be honest, One. What's your impression of me so far?",o:[["Funny 😂","I'll take that. Pressure is officially on for Thursday."],["Interesting 👀","Interesting is good. Let's keep the mystery alive."],["Trouble 🚩","Damn 😭 Thursday is officially my redemption arc."],["Still investigating 🕵🏽‍♀️","Fair. Investigation continues in person."]]},
{tag:"PREDICTION 01",q:"Who do you think will talk more when we finally meet?",o:[["Kartel","Bold prediction. Evidence will be collected Thursday."],["One","Noted 👀 I'm absolutely bringing this up later."],["Both","Best case scenario, honestly."]]},
{tag:"PREDICTION 02",q:"Who makes the other laugh first?",o:[["Kartel 😌","Confidence in me? I like this answer."],["One 😏","Okay then. Challenge accepted."]]}
];
export default function Home(){
const [screen,setScreen]=useState("intro"),[qi,setQi]=useState(0),[reaction,setReaction]=useState("");
const [song,setSong]=useState(""),[artist,setArtist]=useState(""),[secret,setSecret]=useState("");
const [noCount,setNoCount]=useState(0),[noPos,setNoPos]=useState({x:0,y:0});
const answer=(msg)=>{setReaction(msg);setTimeout(()=>{if(qi<questions.length-1){setQi(qi+1);setReaction("")}else setScreen("music")},850)};
const dodge=()=>{if(noCount>=3)return;setNoCount(n=>n+1);setNoPos({x:Math.round(Math.random()*140-70),y:Math.round(Math.random()*70-35)})};
const q=questions[qi];
return <main className="shell"><div className="grain"/><header><span>BEFORE.THURSDAY</span><span className="status"><i/>PRIVATE BUILD</span></header>
{screen==="intro"&&<section className="hero fade"><p className="kicker">ONE, THIS ONE'S FOR YOU.</p><h1>We haven't even<br/>met yet.</h1><p className="lead">And somehow you already got your own website.<br/>Don't get used to this. 😂</p><button className="primary" onClick={()=>setScreen("game")}>Enter the experiment <b>→</b></button><p className="signature">Designed by <strong>Kartel</strong> · for one person only</p></section>}
{screen==="game"&&<section className="panel fade"><div className="progress"><span style={{width:`${((qi+1)/questions.length)*100}%`}}/></div><p className="kicker">{q.tag} · 0{qi+1}/0{questions.length}</p><h2>{q.q}</h2><div className="options">{q.o.map(([a,m])=><button key={a} disabled={!!reaction} onClick={()=>answer(m)}><span>{a}</span><b>↗</b></button>)}</div><p className="reaction">{reaction}</p></section>}
{screen==="music"&&<section className="panel fade"><p className="kicker">SET THE MOOD · 🎧</p><h2>Every good story needs a soundtrack.</h2><p className="sub">What's your favourite song right now? I promise I'll listen before Thursday.</p><div className="form"><label>SONG<input value={song} onChange={e=>setSong(e.target.value)} placeholder="Song title"/></label><label>ARTIST<input value={artist} onChange={e=>setArtist(e.target.value)} placeholder="Artist"/></label></div><button className="primary" disabled={!song.trim()} onClick={()=>setScreen("ice")}>Lock it in 🎧</button></section>}
{screen==="ice"&&<section className="panel center fade"><div className="ice">🍦</div><p className="kicker">WAIT. IMPORTANT.</p><h2>We're getting ice cream on Thursday, right?</h2><p className="sub">{["Choose carefully.","Hmm. Button malfunction detected. 🤔","JavaScript seems to disagree with you 😂","Okay okay 😭 you can actually say no."][Math.min(noCount,3)]}</p><div className="choice"><button className="primary" onClick={()=>setScreen("secret")}>Obviously 🍦</button><button className="no" style={{transform:`translate(${noPos.x}px,${noPos.y}px)`}} onMouseEnter={dodge} onTouchStart={dodge} onClick={()=>noCount>=3?setScreen("secret"):dodge()}>{noCount>=3?"Fine, no 😂":"No"}</button></div></section>}
{screen==="secret"&&<section className="panel fade"><p className="kicker">ONE LAST THING · 🔒</p><h2>Ask me something you're curious about.</h2><p className="sub">Anything. I'll answer it properly when we meet.</p><textarea value={secret} onChange={e=>setSecret(e.target.value)} maxLength={180} placeholder="Your question for Kartel..."/><div className="counter">{secret.length}/180</div><button className="primary" disabled={!secret.trim()} onClick={()=>setScreen("locked")}>Lock until Thursday 🔒</button></section>}
{screen==="locked"&&<section className="panel center fade"><div className="lock">✓</div><p className="kicker">ENCRYPTION COMPLETE</p><h2>Question locked.</h2><div className="musicCard"><span>ONE'S PICK</span><strong>♫ {song}</strong><small>{artist||"artist classified"}</small></div><button className="primary" onClick={()=>setScreen("final")}>Finish →</button></section>}
{screen==="final"&&<section className="final fade"><p className="kicker">ONLINE VERSION ENDS HERE.</p><h1>ONE <em>×</em><br/>KARTEL</h1><p className="lead">Thursday.<br/>No more Instagram. No more website.<br/>Just us finally meeting.</p><div className="line"/><p className="soon">See you soon, One. 🤍</p><button className="easter" onClick={()=>alert("PROJECT: Before Thursday\nDEVELOPER: Kartel\nBUILT FOR: One\nBUGS: Probably\nNERVOUS: Definitely 😂")}>made with questionable amounts of JavaScript.</button></section>}
</main>}